### ISSUE TITLE
Too many tests when running in IDE

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-ogcapi-features10#112]
I am trying to run the tests in Eclipse, as described in section 1 on https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/site/asciidoc/how-to-run-the-tests.adoc

Too many tests are executed:

![image](https://user-images.githubusercontent.com/11427611/86605135-972ce680-bfa6-11ea-845a-b8671ee3604f.png)

When I run the tests using the console (section 2 in https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/site/asciidoc/how-to-run-the-tests.adoc), 15 instead of 18 tests are executed, the tests present in org.opengis.cite.ogcapifeatures10.conformance.ConformanceTest are not run.

![image](https://user-images.githubusercontent.com/11427611/86605290-cc393900-bfa6-11ea-8b62-099e2b44b96a.png)

Is there a way to make sure that tests present in src/test/java are not run when using org.opengis.cite.ogcapifeatures10.TestNGController ?

**Comment by heidivanparys** [comment]
I guess the answer would be updating testng.xml . My main issue was actually the failing test testParseAndValidateRequirementClasses, I was worried that that was the cause of some my other issues when trying to test a Web API. See #113 .

**Comment by ghobona** [comment]
@heidivanparys I think your proposed [edit](https://github.com/opengeospatial/ets-ogcapi-features10/pull/113/files#diff-33cc6f106f765467a8ff31fc293e0df2) fixes the issue of the test testParseAndValidateRequirementClasses.

**Comment by heidivanparys** [comment]
@ghobona  Yes, I agree, that edit fixes the issue of the test testParseAndValidateRequirementClasses.

Perhaps a note should be added to https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/site/asciidoc/how-to-run-the-tests.adoc that says that the JUnit tests are also run when using an IDE to execute the test suite?

**Comment by ghobona** [comment]
@heidivanparys I agree, we will need to update the guidance on that page.

In the meantime, please note that you can run the Compliance tests without executing the JUnit tests by following the steps in the attached screenshots.

[RunningETSfromTestNGController.pdf](https://github.com/opengeospatial/ets-ogcapi-features10/files/4886126/RunningETSfromTestNGController.pdf)

**Comment by dstenger** [comment]
Actually, after having applied your fix, the unit tests should not be executed when running the TestNG tests via an IDE.

Can you please check and confirm if there are any open questions?

**Comment by heidivanparys** [comment]
I have no more open questions, thanks for following up.
