### ISSUE TITLE
Link with "self" relation type for feature collection

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#114]
In relation to this suggestion https://github.com/opengeospatial/ogcapi-features/issues/410#issuecomment-654286272

I suggest we comment out the assertion https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeatureCollections.java#L122

**Comment by heidivanparys** [comment]
> I suggest we comment out the assertion https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeatureCollections.java#L122

Please note that #410 is about missing requirements in section 7.14 Feature collection, whereas the code referenced above tests a requirement from section 7.13 Feature collections.

Regarding the suggestion, I think that for INSPIRE, it can be solved with INSPIRE-MIF/gp-ogc-api-features#39 .

**Comment by ghobona** [comment]
@heidivanparys Ok, understood. We'll review the spec and ETS again to determine a course of action.

**Comment by ghobona** [comment]
Closing this issue because, after discussion with CITE engineers, the conclusion is that the CITE tests do not support warnings for recommendations that have not been implemented. This is because TEAM Engine only reports additional messages on skipped or failed tests, rather than on passed tests.
