### ISSUE TITLE
ETS should take into account different ways of defining servers and paths

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-ogcapi-features10#117]
The ETS should take into account the 2nd variant of defining an API as described in https://github.com/opengeospatial/ogcapi-features/issues/427

At first inspection, code changes would be required in `org.opengis.cite.ogcapifeatures10.openapi3.OpenApiUtils.retrieveTestPoints(OpenApi3, URI, String, PathMatcherFunction<Boolean, String, String>, boolean)` and in the `processServerObjects` methods. The iut URL should be used as input as well, in order to find the correct paths and resource URLs.

**Comment by heidivanparys** [comment]
`OpenApiUtils.retrieveTestPointsForCollectionMetadata(OpenApi3, URI, String)` seems to require a code change too.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by dstenger** [comment]
@heidivanparys Is it possible to provide a test service using the second variant of opengeospatial/ogcapi-features#427?

**Comment by heidivanparys** [comment]
@dstenger I sent a test service via mail.

**Comment by keshav-nangare** [comment]
@dstenger 

I have added a new method that will retrieve the base path using `operationId = getLandingPage`. The base path will be used to get other path's values. You can see the base path in the below screenshot for different services:

![Capture](https://user-images.githubusercontent.com/14732650/93081179-7bcc0f00-f6ac-11ea-84b1-be05333dbe69.PNG)

**Comment by cportele** [comment]
Please note that there is no requirement to provide an `operationId` or to provide a specific value. So, if I understand the proposed change correctly, this will not solve the issue, but rather create new problems.

The URI of the landing page is the value of `iut`. This should be used to determine the path object of the landing page.

**Comment by dstenger** [comment]
@heidivanparys Can you try to use https://my.url.com/v1/mydata (taken from example opengeospatial/ogcapi-features#427) as test input? Does the test suite work correctly then?

**Comment by dstenger** [comment]
@keshav-nangare I just re-checked the implementation and, as the path objects of the OpenAPI document are used, the implementation of the test suite must be updated here.
As cportele proposed, we can use the value of `iut` which is the URL to the landing page to determine the path objects. You could use the servers object of the OpenAPI document by excluding it from iut to retrieve the correct path object value of the landing page and other resources.
Example of opengeospatial/ogcapi-features#427:
- `iut` = https://my.url.com/v1/mydata/
- `servers url` = https://my.url.com
- Exclude `servers url` from `iut` = /v1/mydata/
- /v1/mydata/ = path object value of landing page
- This workflow can also be applied to all other resources

@heidivanparys Thus, the test proposed in comment https://github.com/opengeospatial/ets-ogcapi-features10/issues/117#issuecomment-693253889 becomes obsolete as there is a bug in the implementation of the test suite.

**Comment by heidivanparys** [comment]
@dstenger ok, no problem, I didn't start testing yet.

**Comment by keshav-nangare** [comment]
[1] **iut:** 
      -  a] https://services.interactive-instruments.de/t15/daraa 
      -  b] https://my.url.com/v1/mydata

I went through the implementation again found some pointers which are used for test execution.

1. We get langindgPage information by using `iut[1]` and the test suite will assign `href` value to `apiUrl` from `rel : service-desc`.
2. The response of `apiUrl` will set to `API_MODEL` which is used in further tests as we can see below:

https://github.com/opengeospatial/ets-ogcapi-features10/blob/f470d0067da7cd9ac0668f21aa0fc7f1d101b551/src/main/java/org/opengis/cite/ogcapifeatures10/apidefinition/ApiDefinition.java#L82-L91

3. The same `API_MODEL` is used to match paths or to get other resource paths. FYI:

https://github.com/opengeospatial/ets-ogcapi-features10/blob/f470d0067da7cd9ac0668f21aa0fc7f1d101b551/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/Conformance.java#L40-L50

4. As per your suggestion I tried to apply this workaround but found a difference between the path object value of landing page(`t15/daraa`) and `API_MODEL`. 

We can see the difference between IUT URL path object and API MODEL response `paths` in below screenshot:


**IUT URL:**
[1]http:// services.interactive-instruments.de/`t15/daraa/`

**API_MODEL Response:**
![Screenshot](https://user-images.githubusercontent.com/14732650/93475421-34e15200-f916-11ea-87c6-d46f5e460c2c.png)

@dstenger 

What are your thoughts on the above case? Whether this case is valid or not?

**Comment by dstenger** [comment]
Your last screenshot shows the most common case which is described by first approach of https://github.com/opengeospatial/ogcapi-features/issues/427.
The servers object contains the url to the landing page and that leads to a path of "/" to retrieve the landing page.

**Comment by keshav-nangare** [comment]
@dstenger 

I have updated tests to retrieve the remaining path from the match of `iut` and the `server url`, so changes tested successfully with provided service and pushed into the same branch.
