### ISSUE TITLE
Using Docker instructions always yields "UnknownHostException"

### ISSUE THREAD

**Issue by notthatbreezy** [opengeospatial/ets-ogcapi-features10#118]
I am using the docker instructions to try and execute the test suite, yet no matter what URL I use the test ends with a failure of `UnknownHostException`.

For instance, using the example server (`https://services.interactive-instruments.de/t15/daraa/`) from the documentation [here](https://opengeospatial.github.io/ets-ogcapi-features10/) I get the following:

```
Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.ogcapifeatures10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: services.interactive-instruments.de
Result: Failed
```

![image](https://user-images.githubusercontent.com/898060/92952618-4619f280-f42e-11ea-8669-d7cf5643892e.png)

I started the test suite using `docker run -p 8081:8080 ogccite/ets-ogcapi-features10` in case that helps debug the problem.

**Comment by dstenger** [comment]
Can you please check if the test runs successfully on the environment of OGC?
https://cite.opengeospatial.org/teamengine/

However, the test suite should also work on your local machine. It seems that the host cannot be found (`UnknownHostException: services.interactive-instruments.de`). Maybe the network configuration is not correct so that the Docker Container cannot access the internet?

**Comment by ghobona** [comment]
@notthatbreezy I have just tried the test suite after launching it using the docker command in your initial post. The test suite appears to work fine. Please see attached. Could you please try again? You might need to pull a new docker image from docker hub to be certain that you have the latest image.

<img width="1422" alt="Screenshot 2021-06-29 at 17 23 22" src="https://user-images.githubusercontent.com/18121038/123834171-078eef00-d8ff-11eb-8bb6-99812089832d.png">

**Comment by ghobona** [comment]
@notthatbreezy We have tested the docker TEAM Engine image on multiple machines and it appears to be working fine.  Could you please check the network configuration of your docker container?

If we do not hear from you, we will close this issue on 2021-07-12.
