### ISSUE TITLE
Test suite runs out of memory for some implementations

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#123]
Please see attached. We need to adjust the limit down from 5000 to a smaller number (e.g. 100).

Please use this service to test https://demo.ldproxy.net/vineyards

![Screenshot 2020-09-28 at 11 55 07](https://user-images.githubusercontent.com/18121038/94424290-e2a7f880-0181-11eb-86d0-de1f7afdb742.png)

**Comment by keshav-nangare** [comment]
Fixed with #126 PR.
