### ISSUE TITLE
Add support for OGC API - Features - Part 2: Coordinate Reference Systems by Reference

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#127]
[OGC API - Features - Part 2: Coordinate Reference Systems by Reference](http://docs.opengeospatial.org/DRAFTS/18-058.html) has passed its TC vote. 

Please extend the ETS to include conformance tests from Part 2.

**Comment by ghobona** [comment]
Agenda

* Introductions
* Confirm how the deliverable will be completed
* - Extension of existing ETS, as a separate a branch
* Timetable / schedule
* Risks (go through ATS and plan ahead for any potential risks/problems)

**Comment by dstenger** [comment]
Implementation issues:

- https://github.com/opengeospatial/ets-ogcapi-features10/issues/151
- https://github.com/opengeospatial/ets-ogcapi-features10/issues/152
- https://github.com/opengeospatial/ets-ogcapi-features10/issues/153

**Comment by dstenger** [comment]
Meeting 2021-05-18:

- Limitation of tested features to e.g. 100 (should be configurable via properties file).
- Possible risks:
  - Possible libraries to execute CRS related operations: geotoolkit (geomatics-geotk), apache-sis, proj
  - Decision: Go with geotoolkit (geomatics-geotk), if there are any blocking problems, proj might be an alternative.
    - Reason: Other test suites use geotoolkit (geomatics-geotk) and as all test suites share the same classpath when deployed to TEAM Engine, problems might occur if we use another library (especially apache-sis).

**Comment by dstenger** [comment]
Branch for development of tests: https://github.com/opengeospatial/ets-ogcapi-features10/tree/part2

**Comment by dstenger** [comment]
Items to discuss in next meeting:
- Can we use Jenkins of OGC CITE team?

**Comment by dstenger** [comment]
Meeting 2021-05-25:

> Can we use Jenkins of OGC CITE team?

Yes, we can use the Jenkins of OGC CITE team.

**Comment by dstenger** [comment]
**Meeting 2021-06-01**

* lat/lon checks https://github.com/opengeospatial/ets-ogcapi-features10/issues/140 as it is also related to CRS.

**Comment by dstenger** [comment]
To discuss:
- Limit feature related tests to exactly one feature?

**Comment by dstenger** [comment]
Decisions made in meeting 2021-06-22:

> Limit feature related tests to exactly one feature?

Limit to one feature is fine as this approach was also used in implementation of Part 1.

> Use https://github.com/locationtech/proj4j for transformation of geometries and current JTS version for GeoJSON parser and geometry model?

Using proj4j is fine and was already evaluated.

**Comment by dstenger** [comment]
Pull request was created: https://github.com/opengeospatial/ets-ogcapi-features10/pull/169

Please see https://github.com/opengeospatial/ets-ogcapi-features10/issues?q=label%3A%22Part+2%22+is%3Aclosed for all issues which were solved.
