### ISSUE TITLE
Production (1.0) test fails on GC overhead limit exceeded

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-features10#135]
The production (1.0) version of the test (https://cite.opengeospatial.org/teamengine/) fails on _"GC overhead limit exceeded"_, sometimes on the conformance classes, sometimes on the API, while with the Beta (1.1) version (https://cite.opengeospatial.org/te2/) our implementation passes the Features Core conformance class successfully.

Testing with https://maps.ecere.com/ogcapi and _noOfCollections_ = 5.
The list of collections at https://maps.ecere.com/ogcapi/collections?f=json (2.9 MB) has quite a few collections.

**Comment by dstenger** [comment]
Thank you for reporting.

@keshav-nangare Can you please try to reproduce the reported behavior? Afterwards, we can discuss about a solution.

**Comment by dstenger** [comment]
@keshav-nangare Can you please also test with version 1.0 on Docker?

**Comment by keshav-nangare** [comment]
@dstenger I tried on docker and it is working fine.

**Comment by dstenger** [comment]
Production will be updated to version 1.1 in summer.
Until then, Beta can be used to validate big collections.
