### ISSUE TITLE
Implement test for Abstract Test 2 /ats/core/crs84

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#140]
http://docs.ogc.org/is/17-069r3/17-069r3.html#_crs_84

**Comment by ghobona** [comment]
Also linked to Abstract Test 10. Some initial code for Abstract Test 10 is [here](https://github.com/opengeospatial/ets-ogcapi-features10/blob/24d39d2e758234a9d8db36ba71de37f75051d81f/src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeatureCollections.java#L174).

**Comment by lgoltz** [comment]
PR: #174

> Also linked to Abstract Test 10. Some initial code for Abstract Test 10 is here.
New issue created: #173
