### ISSUE TITLE
Implement test to validate that the required links are included in the Collections document

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#141]
Implement Abstract Test 23 to "Validate that the required links are included in the Collections document"

**Comment by ghobona** [comment]
Could be implemented with fixes for:

* https://github.com/opengeospatial/ets-ogcapi-features10/issues/18
* https://github.com/opengeospatial/ets-ogcapi-features10/issues/19

**Comment by lgoltz** [comment]
Abstract Test 23 is implemented for each features resource ({root}/collections/{collectionId}/items) listed in Abstract Test 14 (without parameter, with parameters limit, boundingbox and datetime) as part of Abstract Test 22. 

The test purpose of Abstract Test 23 is  "Validate that the required links are included in the Collections document." but the test is part of A.2.7. Features {root}/collections/{collectionId}/items. Is the test purpose correct?

**Comment by ghobona** [comment]
@lgoltz You are correct. Abstract Test 23 of v1.0.0 is already implemented as part of Abstract Test 22.

Thanks for the response. I'm closing the issue.
