### ISSUE TITLE
OpenAPI 3.0.3 and out of memory error

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#146]
The ETS appears to run out of memory when processing the new new daraa dataset, which uses OpenAPI 3.0.3

https://demo.ldproxy.net/daraa

However, the Testbed-15 implementation still works with https://services.interactive-instruments.de/t15/daraa, which uses OpenAPI 3.0.2

**Comment by ghobona** [comment]
Cc: @dstenger @cportele

**Comment by cportele** [comment]
I just executed a test run in the IDE and there were no such errors on my machine. So I do not think, it is a general 3.0.3 issue.

[testng-results.txt](https://github.com/opengeospatial/ets-ogcapi-features10/files/6100802/testng-results.txt)

**Comment by ghobona** [comment]
@cportele Ok, thanks. We'll continue to look into the issue.

**Comment by dstenger** [comment]
@keshav-nangare 

Can you please try to reproduce the behavior on following environments?
- https://cite.opengeospatial.org/te3/
- Docker

If you can reproduce it, can you please do a first code analysis to identify the root cause?

**Comment by dstenger** [comment]
@keshav-nangare 

Can you please also test it on https://cite.opengeospatial.org/te2/ as well?

Please document your results in this issue.

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

I am able to reproduce the issue on https://cite.opengeospatial.org/te2/. I will take look into it.

**Comment by dstenger** [comment]
Can you please try to limit the memory of the Docker Container to 1GB and 2GB and try to reproduce the issue on your local machine again?

**Comment by keshav-nangare** [comment]
I tried by limiting the memory of the Docker Container as per the above suggestion but unable to reproduce it. I tried with the 600 MB memory but still it is working fine in docker environment. You can check the below screenshot for the memory limit and used memory.

![Untitled](https://user-images.githubusercontent.com/14732650/112468689-96372180-8d8e-11eb-983d-ff1ac4d584fa.png)

**Comment by ghobona** [comment]
Closing this ticket because Production and Beta TEAM Engine instances appear to work fine with https://demo.ldproxy.net/daraa
