### ISSUE TITLE
Docker image on dockerhub is 5 months old

### ISSUE THREAD

**Issue by afasseco** [opengeospatial/ets-ogcapi-features10#148]
Hi

Thanks for excellent test suite for testing OGC services. This has helped us a great deal during development.

We're starting to use these tests during our build pipeline and we've noticed that the latest image on dockerhub is kinda old:

https://hub.docker.com/r/ogccite/ets-ogcapi-features10/tags?page=1&ordering=last_updated (5 months currently).

Since I can see activity in this repo in the last 5 months I would guess there could be good benefit of distributing a newer build to dockerhub? Could you please push a newer build to dockerhub?

Also good would be continuous releases to dockerhub in the future.

Thanks

**Comment by dstenger** [comment]
Hi,

We are pushing new Docker Images when we are creating a new release of the test suite.
As the latest release is 5 month old (https://github.com/opengeospatial/ets-ogcapi-features10/tree/1.1), the currently uploaded Image is the correct one.

However, if you you are interested in building a newer Image with the current developer version, you can always build it by yourself:
* Clone this repository.
* Build the Docker Image with following Maven command (Maven and Java 8 must be installed): `mvn clean install -Pdocker`
* Please be aware that Docker must also be installed and the user executing Maven must have the permissions to execute Docker.

Does this answer you questions? If there is no further question open, can you please close this issue?

**Comment by afasseco** [comment]
Hi

That makes complete sense. I just assumed that the commits since last release would be grounds for a release but I understand your point.

Thanks for the image building instructions - we will use this in case the the master branch has something not released yet.

I will close this issue thanks for feedback.
