### ISSUE TITLE
Implement tests of "A.1. Discovery" of Part 2

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#151]
[A.1. Discovery](https://docs.opengeospatial.org/is/18-058/18-058.html#_discovery) contains:

- [x] Abstract Test 1 | /conf/crs/crs-uri
- [x] Abstract Test 2 | /conf/crs/default-crs
- [x] Abstract Test 3 | /conf/crs/storageCrs

Reference: [OGC API - Features - Part 2: Coordinate Reference Systems by Reference, Version: 1.0, Publication Date:  2020-11-02](https://docs.opengeospatial.org/is/18-058/18-058.html)

**Comment by lgoltz** [comment]
> Abstract Test 1 | /conf/crs/crs-uri

Implementation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/7497d35efeb642455cc0558e863a060de097b0b2

**Comment by lgoltz** [comment]
> Abstract Test 2 | /conf/crs/default-crs

Implementation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/29dfc222bb7f26affd74b0b0fc04e8a4ab6b3749

If the crs list is referenced in a collection object in the path /collections (with '#/crs') the test of the collection in the path /collections is skipped.

**Comment by lgoltz** [comment]
> Abstract Test 3 | /conf/crs/storageCrs

Implementation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/34e718bd33a7b43e7a24312d625c0358695fccfc

**Comment by dstenger** [comment]
All tests are implemented.
Functional testing was done with https://demo.ldproxy.net/daraa.
