### ISSUE TITLE
Implement tests of "A.2.1. Parameter crs" of Part 2

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#152]
[A.2.1. Parameter crs](https://docs.opengeospatial.org/is/18-058/18-058.html#_parameter_crs_2) contains:

- [x] Abstract Test 4 | /conf/crs/crs-parameter
- [x] Abstract Test 5 | /conf/crs/crs-parameter-invalid
- [x] Abstract Test 6 | /conf/crs/crs-parameter-default
- [x] Abstract Test 7 | /conf/crs/crs-parameter-transform

Reference: [OGC API - Features - Part 2: Coordinate Reference Systems by Reference, Version: 1.0, Publication Date:  2020-11-02](https://docs.opengeospatial.org/is/18-058/18-058.html)

**Comment by lgoltz** [comment]
> Abstract Test 4 | /conf/crs/crs-parameter
Implementation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/8335933afd1113bcdffe2bd553e14ec24b83d2ac, https://github.com/opengeospatial/ets-ogcapi-features10/commit/f312cd13a9066e1d2d214ef666724ea8b580af1c, https://github.com/opengeospatial/ets-ogcapi-features10/commit/8a191be3556df0dfa448b7ed00ba466beb9e589e

> Abstract Test 5 | /conf/crs/crs-parameter-invalid
Implementation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/891f407dbb91dc3fa871c2a4dde7d8f3461eb9b6

**Comment by lgoltz** [comment]
> Abstract Test 6 | /conf/crs/crs-parameter-default

Implementation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/4749d9b356076dfe7e28536c1bd6b00409eb04e5

**Comment by lgoltz** [comment]
> Abstract Test 7 | /conf/crs/crs-parameter-transform

It is required to parse the geometry from the GeoJson response. JTS provides a GeoJsonReader since ~[1.15](https://github.com/locationtech/jts/blob/master/doc/JTS_Version_History.md#version-115) https://github.com/locationtech/jts/blob/master/modules/io/common/src/main/java/org/locationtech/jts/io/geojson/GeoJsonReader.java

**Comment by dstenger** [comment]
**Meeting 2021-06-08**

* Update of JTS
  * JTS can be updated in geomatics-geotk project.
  * 4 test suites are using geomatics-geotk: https://github.com/search?l=Maven+POM&q=geomatics-geotk&type=Code
  * Afterwards, the four other test suites must be checked and updated as well.

**Comment by lgoltz** [comment]
Update of JTS in https://github.com/opengeospatial/geomatics-geotk/issues/10

**Comment by lgoltz** [comment]
All test implemented as specified in the abstract test suite.

**Comment by dstenger** [comment]
All tests were implemented.
