### ISSUE TITLE
Implement tests of "A.2.2. Parameter bbox-crs" of Part 2

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#153]
[A.2.2. Parameter bbox-crs](https://docs.opengeospatial.org/is/18-058/18-058.html#_parameter_bbox_crs_2) contains:

- [x] Abstract Test 8 | /conf/crs/bbox-crs-parameter
- [x] Abstract Test 9 | /conf/crs/bbox-crs-parameter-invalid
- [x] Abstract Test 10 | /conf/crs/bbox-crs-parameter-default

Reference: [OGC API - Features - Part 2: Coordinate Reference Systems by Reference, Version: 1.0, Publication Date:  2020-11-02](https://docs.opengeospatial.org/is/18-058/18-058.html)

**Comment by lgoltz** [comment]
All tests are implemented as specified in the abstract test suite.

**Comment by dstenger** [comment]
All tests were implemented correctly.
