### ISSUE TITLE
Prepare ETS of Part 2

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-ogcapi-features10#154]
* [x] Prepare OGC API ETS
 * [x] Execute Part 2 if requirement class http://www.opengis.net/spec/ogcapi-features-2/1.0/req/crs is supported ([6. Requirements Class Coordinate Reference Systems by Reference](https://docs.opengeospatial.org/is/18-058/18-058.html#_conventions_and_background))

Reference: [OGC API - Features - Part 2: Coordinate Reference Systems by Reference, Version: 1.0, Publication Date:  2020-11-02](https://docs.opengeospatial.org/is/18-058/18-058.html)

**Comment by lgoltz** [comment]
**Prepare OGC API ETS**
Restructured packages: https://github.com/opengeospatial/ets-ogcapi-features10/commit/a5cec66b07ec00929aaafa071135f3ab64665166

**Execute Part 2 if requirement class http://www.opengis.net/spec/ogcapi-features-2/1.0/req/crs is supported**
Added precondition test: https://github.com/opengeospatial/ets-ogcapi-features10/commit/93a433c6d14cd3ef11a1cf3c07f87024b4c0e600

The Test defines the group "crs-conformance", all tests must depend on this group: `@Test(dependsOnGroups = "crs-conformance")`

**Comment by dstenger** [comment]
Test shows that new conformance class is listed in the HTML report of TEAM Engine.
Also, https://demo.ldproxy.net/daraa can be used to execute the first implemented tests.
