### ISSUE TITLE
Enhance ETS documentation - Part 2

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-ogcapi-features10#155]
* [ ] Enhance documentation: https://github.com/opengeospatial/ets-ogcapi-features10/tree/master/src/site

Reference: [OGC API - Features - Part 2: Coordinate Reference Systems by Reference, Version: 1.0, Publication Date:  2020-11-02](https://docs.opengeospatial.org/is/18-058/18-058.html)

**Comment by lgoltz** [comment]
Limitiations:

* Exactly on feature is tested 
* Abstract Tests 7, 8, 10: Transformation is supported for all CRSs starting with urn:ogc:def:crs:EPSG or http://www.opengis.net/def/crs/EPSG

**Comment by dstenger** [comment]
Documentation was enhanced to reference Part 2 as well: https://github.com/opengeospatial/ets-ogcapi-features10/commit/8aa787502418179fb6b78489eee38605b6575a92

**Comment by dstenger** [comment]
Add CRS specific test requirement to documentation: https://github.com/opengeospatial/ets-ogcapi-features10/commit/bf0b2f03b25e912d6a743fdfd594db322de8eed9

**Comment by dstenger** [comment]
I propose to document the limitations in the JavaDoc instead of user documentation.

**Comment by dstenger** [comment]
Documentation in the GUI and REST interface were updated as well:
- GUI: https://github.com/opengeospatial/ets-ogcapi-features10/commit/1b7defb9a598b70cef2ab11bf408b3bc4ab928f6
- REST interface: https://github.com/opengeospatial/ets-ogcapi-features10/commit/b4f3d5b45e92bd841a54e244bd4bd4678a489392

**Comment by dstenger** [comment]
Enhanced documentation by limitation and hints to ATS: https://github.com/opengeospatial/ets-ogcapi-features10/commit/5ca0f4a313080e9faf8e35ce8e9f6fbaef92d1aa
