### ISSUE TITLE
Test implementation of Part 2

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#160]
Branch to be tested: https://github.com/opengeospatial/ets-ogcapi-features10/tree/implementPart2-127

**Comment by dstenger** [comment]
# Test with https://demo.ldproxy.net/daraa

This comment contains the current status and will be updated constantly.

Two tests are failing:
verify Bbox Crs Parameter | java.lang.AssertionError: lists don't have the same size expected <br>[8] but found <br>[0]
verify Bbox Crs Parameter | java.lang.AssertionError: lists don't have the same size expected <br>[10] but found <br>[0]

Four tests are skipped:
verify Collections Path Crs Property Contains Default Crs | org.testng.SkipException: Collections path /collections does not specify a storageCrs
verify Collections Path Collection Crs Property Contains Default Crs | org.testng.SkipException: Collection with id 'AeronauticCrv' at collections path /collections references to global crs section.
verify Collections Path Collection Crs Property Contains Default Crs | org.testng.SkipException: Collection with id 'AeronauticSrf' at collections path /collections references to global crs section.
verify Collections Path Collection Crs Property Contains Default Crs | org.testng.SkipException: Collection with id 'AgriculturePnt' at collections path /collections references to global crs section.

**Comment by dstenger** [comment]
# Test with https://oaf.lat-lon.de/deegree-services-oaf/datasets/kitaeinrichtung

This comment contains the current status and will be updated constantly.

Core tests are failing which did not fail previously. I will create new issues for that.

CRS tests are skipped as the conformance class is not listed in the conformance resource.

**Comment by cportele** [comment]
@dstenger - Thanks for the development. I had a quick look:

> verify Bbox Crs Parameter | java.lang.AssertionError: lists don't have the same size expected <br>[10] but found <br>[0]

These requests state EPSG 4326 in `bbox-crs`, but then continue to use lon/lat in `bbox`, not lat/lon. This is the reason why no features are returned (which is the correct response to the request).

For the skipped tests, all the information seems to be there, so I assume the tests are not complete yet? Or is something missing in the ATS?

**Comment by ghobona** [comment]
@dstenger I tried the ldproxy and deegree implementations got lots of NullPointerExceptions. It might be my TEAM Engine instance. Could you please confirm whether you have tried deploying the ETS in TEAM Engine?

Please see attached.

[s0018.zip](https://github.com/opengeospatial/ets-ogcapi-features10/files/6728783/s0018.zip)

[s0011.zip](https://github.com/opengeospatial/ets-ogcapi-features10/files/6728784/s0011.zip)

[s0016.zip](https://github.com/opengeospatial/ets-ogcapi-features10/files/6728785/s0016.zip)

**Comment by dstenger** [comment]
Sure, I tested with TEAM Engine.
I used following command to start the test suite with Maven and Docker: `mvn clean install docker:run -Pdocker`.

Did you unzip the libraries to the lib folder of the TEAM Engine webapp?

**Comment by ghobona** [comment]
@dstenger I did unzip the libraries to the lib folder but I think there might be an issue with my TEAM Engine instance. 

I'll try the command in the comment above. Thanks.

**Comment by dstenger** [comment]
@cportele Thank you for the feedback.
We created two new issues covering your comments:
* #167
* #168

**Comment by dstenger** [comment]
Both previously mentioned issues were solved.

Now, https://demo.ldproxy.net/daraa is passing all tests.

@cportele Can you please check https://github.com/opengeospatial/ets-ogcapi-features10/issues/167#issuecomment-874076725? We discovered this during the implementation of the fix.

**Comment by cportele** [comment]
Thanks @dstenger.

Regarding the comment in issue 167: Yes, the reference to "axis order" is a left over from an earlier draft status. We will fix this in Part 2.
