### ISSUE TITLE
NullPointerExceptions in tests validate Features Response_ Number Returned and validate Features With Bounding Box Response_ Number Matched

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#161]
Following service was used for testing: https://oaf.lat-lon.de/deegree-services-oaf/datasets/kitaeinrichtung

NullPointerExceptions occur in tests:
* validate Features Response_ Number Returned
* validate Features With Bounding Box Response_ Number Matched

These tests are part of the Core conformance class. However, the failures are related to the implementation of Part 2 as they do not occur on the Beta environment.

**Comment by lgoltz** [comment]
The failure is not related to the implementation of Part 2 but to the big fix #158. Before this big fix the spatial extent could not be parsed and the failing tests was not executed. 
Possible NPE was fixed: https://github.com/opengeospatial/ets-ogcapi-features10/commit/7e705cb7f306d542645c65872b2bb7c0f9f5ab6f
PR: #163
