### ISSUE TITLE
Test validate Features With Bounding Box Response_ Features Property fails unexpectedly

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#162]
Following service was used for testing: https://oaf.lat-lon.de/deegree-services-oaf/datasets/kitaeinrichtung

Test `validate Features With Bounding Box Response_ Features Property` fails with following message: `java.lang.AssertionError: features property is missing expected object to not be null`

This test is part of the Core conformance class. However, the failure is related to the implementation of Part 2 as it does not occur on the Beta environment.

**Comment by lgoltz** [comment]
The tests fails because it requests data with a spatial bbox the service provide data for:
 * -1.5000000,50.0000000,1.5000000,53.0000000 
 *   -80.0000000,-5.0000000,-70.0000000,5.0000000 
 *  -180.0000000,85.0000000,180.0000000,90.0000000 
 *  -180.0000000,-90.0000000,180.0000000,-85.0000000 

The failure is not related to the implementation of Part 2 but to the big fix #158. Before this big fix the spatial extent could not be parsed and the failing tests was not executed.

**Comment by dstenger** [comment]
We propose to improve error message to `java.lang.AssertionError: features property is missing: expected object to not be null`.

**Comment by tfr42** [comment]
For the given bboxes the service kitaeinrichtung does not return data (numberMatched and numberReturned = 0). The test https://github.com/opengeospatial/ets-ogcapi-features10/blob/4daa6b229189794486326a3cc87934e4812ebc67/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/AbstractFeatures.java#L104 checks for the existence of a features property which does not exist. 
The deegree OAF implementation needs to be improved by returning an empty features property, such as: 
```
"features":[]
```

**Comment by dstenger** [comment]
Issue was resolved in deegree implementation.

**Comment by dstenger** [comment]
Error message was improved: https://github.com/opengeospatial/ets-ogcapi-features10/commit/2e31ba115dcc65b453bcebab402f9c2f46438b04

**Comment by murithigeo** [comment]
Anyone know why the exact same bboxs are failing? 
If no features are found, the featurecollection object should return an empty features array?

**Comment by dstenger** [comment]
Thank you for responding.
Can you please open a new issue as this one is already closed?
Is your question targeting the test suite or the specification? Can you also please reference the failing test with the associated failure message? Also, a test API to reproduce the problem is always useful for us (if available).

**Comment by murithigeo** [comment]
Sorry about the irreproducability. I'm developing a Postgres +Node Js app and the dataset is quite large and that is not accounting for the fact that its a hustle if the tester does not have the database on his machine. I did notice that TE expects an empty array if no features match. I will have to find some way to host the database for easy debugging.
