### ISSUE TITLE
Fix JavaDoc

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-ogcapi-features10#165]
1. The description of DiscoveryCollectionDefaultCrs.verifyCollectionCrsIdentifierOfCrsProperty() says it implements Abstract Test 1.
However, the name of the class and the comments on the Class suggest that it implements Abstract Test 2.
2. The description of DiscoveryCollectionStorageCrs.verifyCollectionCrsIdentifierOfCrsProperty() says it implements Abstract Test 2.
However, the name of the class and the comments on the Class suggest that it implements Abstract Test 3.
3.  The description of FeaturesCrsParameter.verifyFeaturesCrsParameter() says it implements Abstract Test 1.
However, the name of the class and the comments on the Class suggest that it implements Abstract Test 4.
4. The description of  FeaturesCrsParameterInvalid.verifyFeaturesCrsParameterInvalid() says it implements Abstract Test 1.
However, the name of the class and the comments on the Class suggest that it implements Abstract Test 5.

**Comment by lgoltz** [comment]
Fixed with https://github.com/opengeospatial/ets-ogcapi-features10/commit/eadcbc567edef3cd848d52ae0cb4c9d25c43cb96

**Comment by dstenger** [comment]
JavaDoc was fixed correctly.
