### ISSUE TITLE
UriBuilder.retrieveCollectionNameTemplateName does not support prefix in testPoint path

### ISSUE THREAD

**Issue by alainbodiguel** [opengeospatial/ets-ogcapi-features10#177]
**Describe the bug**
Use of paths with a prefix makes the test "Implements A.2.6. Feature Collection {root}/collections/{collectionId}, Abstract Test 12 (Requirement /req/core/sfc-md-success)"  failed

**To Reproduce**
1. Example TestPoint: `testPoint=Server URL: http://localhost:9999/myservice, Path: /stac/collections/{collectionId}, Replacements: {}`
2. Run the tests
3. Test "Implements A.2.6. Feature Collection {root}/collections/{collectionId}, Abstract Test 12 (Requirement /req/core/sfc-md-success)" fails as it tries to find the property "id" in the result of `/collections/` instead of `/collections/{collectionId}`

**Expected behavior**
The test should succeed.

**Additional context**
* IUT defined in test-run-props.xml as `http://localhost:9999/myservice/stac/`
* `servers.url` in OpenAPI v3 is set to `http://localhost:9999/myservice`
* Endpoints in OpenAPI v3 are all defined with prefix `/stac/...`
* `UrIBuilder.retrieveCollectionNameTemplateName` expects the path to starts with `/collections`
* all other tests pass

**Comment by alainbodiguel** [comment]
Not yet. Might be in a near future, we'll let you know if/when it is the case.
Thank you!

**Comment by dstenger** [comment]
Might be related to #117.
