### ISSUE TITLE
Prevent NPE in FeaturesAssertions

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#178]
In `org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesAssertions.java:96`
```
                maximumLimit = limitParameter.getSchema().getMaximum().intValue();
```

there occurs a NullPointerException if the schema does not define maximum.

The error message shall be improved.

Also, it should be checked if a similar NPE can occur in other methods as well.

**Comment by bpross-52n** [comment]
Instead of creating an error message, a check for null was introduced in #208. The maximum can be undefined, according to the standard.
