### ISSUE TITLE
Assert that features in response are in requested BoundingBox

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-ogcapi-features10#18]
Test: org.opengis.cite.wfs30.collections.GetFeaturesOperation#validateBboxParameter_requests()

Abstract Test 22, Method 3

**Comment by ghobona** [comment]
Implementation pending in [org.opengis.cite.ogcapifeatures10.collections.FeaturesBBox.validateFeaturesWithBoundingBoxResponse](https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesBBox.java#L178)

**Comment by ghobona** [comment]
@keshav-nangare 

Verified using OpenAPITools Generator that bbox is supposed to be structured like:

```json
            "extent": {
                "spatial": {
                    "bbox": [
                        [
                            11.0,
                            21.0,
                            31.0,
                            41.0
                        ]
                    ],
                    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
                }
            }
```

So the ETS should be enabled to handle this.

**Comment by keshav-nangare** [comment]
Thanks, @ghobona, I will update ETS for the same.

**Comment by keshav-nangare** [comment]
The `parseSpatialExtent` method updated to trigger the unimplemented test. Please find the changes in #149 PR.

**Comment by dstenger** [comment]
Method was moved to https://github.com/opengeospatial/ets-ogcapi-features10/blob/68601b530be4a0765a50f445444e80b9a8094d27/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox.java#L181
