### ISSUE TITLE
Api links with relative paths not supported

### ISSUE THREAD

**Issue by trucheromayor** [opengeospatial/ets-ogcapi-features10#180]
**Describe the bug**
Test for validating Confermance Operation and Response failed. This issue seems to appear when having paths with a relative base path.

**To Reproduce**
1. Go to https://cite.opengeospatial.org/teamengine/ register a create an account
2. Perform OGC Features API test with the following url: "https://gisco-development.northeurope.cloudapp.azure.com/features/"

**Expected behavior**
Most of the tests to be passed

**Screenshots**
Test not passed:
![image](https://user-images.githubusercontent.com/5648254/138706831-26b6b6b6-d939-477b-a2e1-e225b3730837.png)
Current schema
![image](https://user-images.githubusercontent.com/5648254/138701737-a5e4aa9b-692a-4bb0-82f4-a6d442961d8b.png)

**Additional context**
A solution for this has been proposed in the following [PR](https://github.com/opengeospatial/ets-ogcapi-features10/pull/179)

**Comment by dstenger** [comment]
@trucheromayor Are you fine closing this issue as the related PR is closed?
