### ISSUE TITLE
Improve tests performance

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-features10#183]
**Is your feature request related to a problem? Please describe.**
Executing the tests on our [implementation](https://maps.ecere.com/ogcapi) takes a good 30 minutes even when testing only 3 collections.
 I don't think it is because of processing or data transfer time on our end. It is also a lot more time than the sum of the duration of the tests, most of which are under 1s except for 4 that take up to ~1min30s. Opened a separate issue (#182) about the lack of progress indicator during that time, which originally had me think the tests were stuck.

**Describe the solution you'd like**
The tests should complete relatively quickly, in about the amount currently reported in the test report.

**Comment by dstenger** [comment]
Thank you for reporting.

This problem is most likely related to the number of features provided by the collections.

**Comment by jerstlouis** [comment]
Thank you @dstenger .
I believe the test uses the first 3 listed vector collections on our server which are:

[NaturalEarth:cultural:ne_10m_admin_0_boundary_lines_maritime_indicator](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_boundary_lines_maritime_indicator) (_220 features_)
[NaturalEarth:cultural:ne_10m_admin_0_antarctic_claims](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_antarctic_claims/items?f=json&omitGeometry=true) (_10 features_)
[NaturalEarth:cultural:ne_10m_admin_0_sovereignty](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_sovereignty) (_206 features_)

I wouldn't consider this a large number of features -- we are planning to eventually host the full 60+GB Planet OpenStreetMap dataset which has over a billion features.

Ideally the tests should work without requesting every single feature and/or otherwise allow the user to explicitly list collections of a reasonable size to test.

**Comment by dstenger** [comment]
@jerstlouis We cannot reproduce the test run of 30 minutes anymore. However, we agree that the performance can be improved. Issue #202 was created to improve the performance of the test suite.
If you agree, I propose to close this issue.

**Comment by jerstlouis** [comment]
Thanks @dstenger . Closing. I will reopen with more details if I run into a similar 30 minutes wait again.

What would be really great is to have a continuously updating log of visible to the user in the client window of which requests are being sent to the server.
