### ISSUE TITLE
Abstract Test 13 clarification

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-ogcapi-features10#187]
**Describe the bug**
Abstract Test 13 is possibly sending an items query with an erroneous `bbox` parameter,

**To Reproduce**
1. Run a CITE session against https://demo.pygeoapi.io/cite
2. Click on error at line `java.lang.AssertionError: 1 expectation failed. Expected status code <200> but was <400>`

**Expected behavior**

The ETS should send a valid bbox to the OAFeat server, or if it is sending an invalid `bbox` by design, allow for a 400 response.

**Screenshots**
![image](https://user-images.githubusercontent.com/910430/147426741-27f24ae2-4599-4d70-9cdc-5e3c99cf7751.png)

https://demo.pygeoapi.io/cite/collections/canada-hydat-daily-mean-02hc003/items?bbox=177.0000000%2C65.0000000%2C-177.0000000%2C70.0000000

**Additional context**
`Request params: bbox=177.0000000,65.0000000,-177.0000000,70.0000000` (looks like minx > maxx?)

**Comment by dstenger** [comment]
Thank you for reporting.

The code leading to this bounding box is found here:

https://github.com/opengeospatial/ets-ogcapi-features10/blob/cf0ebe3debbf55183a68f1a09f9edaaad1063712/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox.java#L40-L60

The pre-defined bounding boxes are not required by the standard anymore but were part of an earlier version of the standard (pre-version).

I also agree that your referenced bounding box looks strange.

However, I propose to remove all predefined bound boxes from the test suite as they are not required anymore.

**Comment by cportele** [comment]
> Abstract Test 13 is possibly sending an items query with an erroneous bbox parameter

A bounding box `177.0, 65.0, -177.0, 70.0` is a valid bounding box that crosses the antimeridian and the result must be a 200 not a 400. The spec says:

> For WGS 84 longitude/latitude the values are in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the antimeridian the first value (west-most box edge) is larger than the third value (east-most box edge).

**Comment by dstenger** [comment]
@cportele Thank you for clarification.

Thus, there is no actual need to remove the pre-defined bounding boxes.

**Comment by tomkralidis** [comment]
Thanks for the clarification, makes sense.  pygeoapi [has been updated](https://github.com/geopython/pygeoapi/pull/837) as a result and now passes this test.  Thank you CITE!
