### ISSUE TITLE
OpenAPIUtils.identifyTestPoints misses some paths

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#191]
**Describe the bug**

The `OpenAPIUtils.identifyTestPoints` method  is unable to detect matches between paths that extend from the path being detected. For example, in the following case it was comparing API paths that started with `/api/abc/v1` and it could not match `/api/abc/v1/conformance` to `/conformance`.

```txt
/api/stac/v1/ CHECK /conformance FALSE
/api/stac/v1/conformance CHECK /conformance  FALSE
/api/stac/v1/collections/{collection_id}/items/{item_id} CHECK /conformance  FALSE
/api/stac/v1/search CHECK /conformance  FALSE
/api/stac/v1/collections CHECK /conformance  FALSE
/api/stac/v1/collections/{collection_id} CHECK /conformance  FALSE
/api/stac/v1/collections/{collection_id}/items CHECK /conformance  FALSE
/api/stac/v1/queryables CHECK /conformance  FALSE
/api/stac/v1/collections/{collection_id}/queryables CHECK /conformance  FALSE
```

**To Reproduce**
1. Test the following endpoint https://planetarycomputer.microsoft.com/api/stac/v1.
2. Check whether [identifyTestPoints](https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/main/java/org/opengis/cite/ogcapifeatures10/openapi3/OpenApiUtils.java#L341) detects the `/conformance` path.

**Expected behavior**

Expected the condition to detect that the paths **endsWith** `/conformance`.

**Comment by dstenger** [comment]
Might be related to https://github.com/opengeospatial/ets-ogcapi-features10/issues/117.

**Comment by dstenger** [comment]
When checking the [OpenAPI document](https://planetarycomputer.microsoft.com/api/stac/v1/openapi.json), we detected following:
```
...
  "servers": [
    {
      "url": "/api/stac/v1"
    }
  ],
...
  "paths": {
...
    "/api/stac/v1/conformance": {
...
```

It seems that the path _/api/stac/v1_ is declared multiple times.

**Comment by ghobona** [comment]
@dstenger Ok, thanks. It seems it is not a problem with the ETS. So I'm closing this issue.
