### ISSUE TITLE
Abstract Test 22 - maximum behaviour check if maximum is not specified crashes

### ISSUE THREAD

**Issue by jnystad** [opengeospatial/ets-ogcapi-features10#196]
**Describe the bug**
A maximum limit value is not required. This test should be skipped if limit has no specified maximum.

Crash:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "com.reprezen.kaizen.oasparser.model3.Schema.getMaximum()" is null


(Implements A.2.7. Features {root}/collections/{collectionId}/items, Abstract Test 22, Test Method 6 (Requirement /req/core/fc-response) - Abstract Test 25 (Requirement /req/core/fc-numberMatched))
```

**Expected behavior**
Skip test if no maximum is set.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by ghobona** [comment]
Indeed, the [Abstract Test](https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#ats_core_fc-limit-response) states that "If the API definition specifies a maximum value for `limit` parameter, verify that the count does not exceed this maximum value."

The [code](https://github.com/opengeospatial/ets-ogcapi-features10/blob/a22e77001419ae11e215a7fdf3c8dbe580f49063/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesLimit.java#L55) you are referring to is only executed if the limit parameter is specified in the API definition document.

I do agree that the code mistakenly assumes that if a limit is declared, then both the minimum and maximum limits are declared. The CITE team will look into improving the relevant code to make maximum limit optional, as implied in the Abstract Test.

**Comment by dstenger** [comment]
@jnystad Is it possible that you provide an publicly available API to test our fix?

**Comment by jnystad** [comment]
No, sorry, still no public API available from us.
