### ISSUE TITLE
CRS tests fail against empty feature collections

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-ogcapi-features10#201]
If a collection contains no features, multiple tests will fail against it, for example, because they try to use "null" as a feature identifier.

Given this Features implementation:
https://gs-main.geosolutionsgroup.com/geoserver/ogcapi/ogc/features/v1

The collection "tasmania_no_roads" contains no features.
Three tests fail against it, all trying to work against a single feature, whose id is "null", e.g.:

https://gs-main.geosolutionsgroup.com/geoserver/ogcapi/ogc/features/v1/collections/tasmania_no_roads/items/null?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FOGC%2F1.3%2FCRS84  ("null" as the feature id)

**Comment by dstenger** [comment]
Thank you for reporting.

Indeed, the test suites expects at least one feature per collection. This was introduced to prevent that an API with only empty collections can be certified.
I agree that we could implement a mechanism making sure that at least one collection contains a feature (or even more) and all other collections might be empty.
We will discuss this in the CITE team.

**Comment by aaime** [comment]
Makes sense.

A possibly simpler alternative would be to report that an empty collection is not accepted, rather than using "null" to identify features... but I like your proposal better, as having a temporarily empty collection is a legit situation (especially when transactional is implemented).
