### ISSUE TITLE
400 error (Bad request) when trying to connect to the test suites endpoint (Docker)

### ISSUE THREAD

**Issue by why-not-try-calmer** [opengeospatial/ets-ogcapi-features10#205]
**Describe the bug**
Connecting to the endpoint at `http://<service_name>:8080/teamengine/rest/suites` from a GET request fails on error 400.

**To Reproduce**
1. Start a Docker Compose application with a service running the `ets-ogcapi-features-10` official Docker image, using `ports: [8081:8080]` to make the container accessible from the localhost.
2. Use a programming language (i.e. python's `requests` module) to make a GET request against the URL mentioned above.
3. Witness error 400.

**Expected behavior**
I should be able to see the list of available test suites. The test suites are visible if I make the same request from a browser, using `localhost:8081`.

**Comment by dstenger** [comment]
Thank you for reporting.
Can you give more details of the response?
What exact headers and body were returned?

**Comment by why-not-try-calmer** [comment]
> Thank you for reporting. Can you give more details of the response? What exact headers and body were returned?

Thanks for your quick response. Will do when back home.
