### ISSUE TITLE
1.3/CRS84h required but link is not working

### ISSUE THREAD

**Issue by GinaStavropoulou** [opengeospatial/ets-ogcapi-features10#221]
I am using the test suite to evaluate an API that offers data in CRS84h and 7415. I noticed that the test suite requires the default 3D CRS to be defined with the link (according to docs):
[http://www.opengis.net/def/crs/OGC/1.3/CRS84h](http://www.opengis.net/def/crs/OGC/1.3/CRS84h)

However, it seems that this link is not working anymore (gives an invalid request). 
If I substitute the version from 1.3 to 0, I get a valid link:

[http://www.opengis.net/def/crs/OGC/0/CRS84h](http://www.opengis.net/def/crs/OGC/0/CRS84h)

If I use the working link (0/CRS84h), all the tests are passing apart from the ones which test against the 1.3 version:

<img width="1006" alt="image" src="https://github.com/opengeospatial/ets-ogcapi-features10/assets/94386515/c464bd89-32b6-424b-9e47-7884b2129e7f">

<img width="1510" alt="image" src="https://github.com/opengeospatial/ets-ogcapi-features10/assets/94386515/f2b9a116-43e4-4386-9b39-149ce18673ca">

But if I use the non-working but required link (1.3/CRS84h) I get null pointer exceptions in the tests:

_verify Feature Crs Parameter Transform Without Crs_ 
and 
_verify Features Crs Parameter Transform With Crs Parameter_

<img width="1494" alt="image" src="https://github.com/opengeospatial/ets-ogcapi-features10/assets/94386515/f990ccf0-f528-41ad-a4c9-f54889af8033">

<img width="1424" alt="image" src="https://github.com/opengeospatial/ets-ogcapi-features10/assets/94386515/210daad9-b3d7-4c5c-81ac-feba9c234eba">

I assume these exceptions stem from the non-working link. 

Is it possible that there is another link I should be using or is this a known issue?
And is there a way to identify where these Null pointer exceptions are coming from?

**Comment by dstenger** [comment]
Thank you for reporting.

I agree that http://www.opengis.net/def/crs/OGC/0/CRS84h is the correct identifier (stated by [spec](https://docs.ogc.org/is/17-069r3/17-069r3.html)).
Thus, this must be corrected in the test suite which currently expects http://www.opengis.net/def/crs/OGC/1.3/CRS84h.

**Comment by dstenger** [comment]
Is it possible to provide a test service we can use to reproduce the behavior?

**Comment by GinaStavropoulou** [comment]
Hi @dstenger! Thank you for looking into this. Unfortunately we cannot provide a test service right now.

**Comment by GinaStavropoulou** [comment]
Regarding the specs, I was following [this version](https://docs.ogc.org/is/18-058/18-058.html) but it seems quite inconsistent. This test still expects 1.3 for CRS84h.

<img width="856" alt="image" src="https://github.com/opengeospatial/ets-ogcapi-features10/assets/94386515/9125c50d-068e-4a19-badb-bed90ae71a0d">

**Comment by dstenger** [comment]
Thank you for providing you findings.
We created an issue in the repository of the spec: https://github.com/opengeospatial/ogcapi-features/issues/849

**Comment by GinaStavropoulou** [comment]
I see that this issues has been moved to "todo". Are there any plans of fixing this error soon? Or is there another way for APIs with 3D data to achieve OGC compliance without this test-suite?

**Comment by dstenger** [comment]
@GinaStavropoulou We are currently working on a fix. We plan to install it on Beta environment (https://cite.ogc.org/te2/) in September.

**Comment by ghobona** [comment]
@GinaStavropoulou If you need to certify your product sooner, then please feel free to submit the test results. As the failed test is for a known bug in the ETS, you will be granted an exemption.

**Comment by GinaStavropoulou** [comment]
@dstenger Thank you for looking into this issue. I see that the fix has been merged to main. Will the [docker image](https://hub.docker.com/r/ogccite/ets-ogcapi-features10) also be updated soon? I tried pulling the latest version (from one month ago) and the web browser interface doen't seem to load.

@ghobona regarding the test results, we are still working on them. I will let you know when we will have a working example which then you can use for testing.

**Comment by dstenger** [comment]
@GinaStavropoulou 
New Beta releases (https://cite.ogc.org/te2/) are planned for the end of this week. This will also include an update of the Docker Image on Docker Hub.
The Image uploaded to Docker Hub a month ago should work (of course, it does not include this fix). I just tested it and am able to execute the tests via Web Browser Interface. Can you please describe your problem more in detail (preferably in a new issue as it is not related to this issue)?

**Comment by GinaStavropoulou** [comment]
@dstenger Thank you for the swift reply. I will try again next week. 
Regarding the problem with the latest image, it might be on my side. I will check again and if I still have it I will create an issue.
