### ISSUE TITLE
Incorrect processing of point coordinates

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ets-ogcapi-features10#222]
**Describe the bug**
When I execute the recently updated tests against https://ri.ldproxy.net/daraa for 10 collections, I get two failed tests for test method `validateFeaturesWithBoundingBoxResponse`, but the evaluation of both results is incorrect:

> Geometry 'POINT (35.9535 32.59207)' outside bounding box: '35.9534988,32.5920715,36.1085472,32.6405067'.

The [geometry returned by the feature](https://ri.ldproxy.net/daraa/collections/CulturePnt/items/5?f=json) is `35.9535002 32.5920726`, not `35.9535 32.59207` as reported. The geometry is within the bounding box. 

It looks as if there are some floating point issues when processing the JSON response. The issue seems to be [here](https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/main/java/org/opengis/cite/ogcapifeatures10/conformance/core/collections/AbstractFeatures.java#L352-L353). `response.response.groovyResponse.content` has `... "coordinates":[35.9535002,32.5920726] ...`, but `features.get(3).get("geometry").get("coordinates").toString()` is `[35.9535, 32.59207]`.

> Geometry 'POINT (36.107697 32.63196)' outside bounding box: '36.1047058,32.6297493,36.1076965,32.6429558'.

The [geometry returned by the feature](https://ri.ldproxy.net/daraa/collections/FacilityPnt/items/1?f=json) is `36.1076948 32.6319629`, not `36.107697 32.63196` as reported. The geometry is within the bounding box. The cause is the same as above.

**To Reproduce**
1. Run the ETS against https://ri.ldproxy.net/daraa for 10 collections.
2. Open test report.
3. Search for `FAIL`

**Expected behavior**
No failed tests should be reported.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by dstenger** [comment]
Thank you for reporting.

I am able to reproduce the error and, indeed, there seems to be a floating point issue.
