### ISSUE TITLE
Improved logging in order to follow progress

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-ogcapi-features10#228]
I usually run the tests from within the IDE or on the command line. It is not easy to follow in the console what is going on, how far the progress is, and what tests are run in what order.

A lot of messages in the style below are being shown, but that's about it.

```
Request method:	GET
Request URI:	https://...
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=application/json, application/javascript, text/javascript, text/json
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
```

The logging should be improved, to show what test is being run.

This is perhaps related to #182.

**Comment by dstenger** [comment]
Thank you for providing the pull request.
This is a useful enhancement.
