### ISSUE TITLE
bbox or parameter parsing

### ISSUE THREAD

**Issue by murithigeo** [opengeospatial/ets-ogcapi-features10#231]
**Describe the bug**
The bbox parameter is a 4 or 6 coordinate array. As per the CLI, the bbox query sent is ```http://mydomain.com/collections/incidents/items?bbox=-77.0147260%2C97.5504510%2C55.0115610%2C-10.7743720```. As per OAS3 docs, this is a spaceDelimited style parameter array. 

**Expected behavior**
However, official docs state that the style of the bbox should be ```style: form``` meaning that the query should be ```http://mydomain.com/collections/collectionId/items?bbox=-77.0147260,97.5504510,55.0115610,-10.7743720```

**Additional context**
This issue is also partly discussed here: https://gis.stackexchange.com/questions/448062/how-to-troubleshoot-wfs-bbox-problems.

In essence, I'm seeking advice on what the official and expected behavior should be

**Comment by dstenger** [comment]
Thank you for reporting.

When I decode
`http://mydomain.com/collections/incidents/items?bbox=-77.0147260%2C97.5504510%2C55.0115610%2C-10.7743720`
the result is
`http://mydomain.com/collections/incidents/items?bbox=-77.0147260,97.5504510,55.0115610,-10.7743720`.

So, the bbox parameter value already uses comma delimited values.

Which CLI are you referencing to? The *aio.jar of this test suite?

The link to gis.stackexchange.com is about a WFS service which is a different standard than OGC API Features.

**Comment by murithigeo** [comment]
To be honest, I'm not even sure. I'm using the latest docker image. The query params may be listed as comma delimited values. For instance: bbox=-40,40,40,-40 but the request sent is a `http://mydomain.com/collections/collectionId/items?bbox=-40%2C40%2C40%2C-40`. The server software does not decode the url automatically and enforces parameter styles and properties. Is there a setting to prevent decoding the url using ```
%2C```

**Comment by murithigeo** [comment]
So sorry to waste your time. Just a student trying to make things work without too much experience. But I was able to decode the URL before it was sent to the middleware. Thanks
