### ISSUE TITLE
Not really sure if it's a bug or something else. Part 2: Abstract Test 8

### ISSUE THREAD

**Issue by murithigeo** [opengeospatial/ets-ogcapi-features10#233]
Bug in OGC API - Features - Part 2: Coordinate Reference Systems by Reference. Abstract Test 8

The extent of my collection is: `[-176.176447, -53.154613, 179.366667, 74.633553]` and to conduct Abstract Test 8, a bbox is first sent with `bbox=xmin,ymin,xmax,ymax` and `bbox-crs` is a value included in the `crs` parameter. However, this is the actual request sent: 
`http://192.168.141.59/collections/gtdb/items?bbox-crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F4326&bbox=-53.1546130%2C-176.1764470%2C74.6335530%2C179.3666670`

with its parameters as: `bbox-crs=http://www.opengis.net/def/crs/EPSG/0/4326 bbox=-53.1546130,-176.1764470,74.6335530,179.3666670`
As you can see, its doing the query as `bbox=ymin,xmin,ymax,xmax`

So my question is whether there is a reason for the deviation from format was previously used.

**Comment by cportele** [comment]
The request (and the test) is correct. 

The CRS `http://www.opengis.net/def/crs/EPSG/0/4326` has axis order latitude/longitude. As a result, [the values in the `bbox` parameter](https://docs.ogc.org/is/17-069r4/17-069r4.html#_parameter_bbox) have to be as it is in the request:

- south latitude
- west longitude
- north latitude
- east longituide

**Comment by murithigeo** [comment]
Thanks. I'm using PostGIS which uses long lat for EPSG:4326 so I was very confused
