### ISSUE TITLE
Clarification on numberMatched and numberReturned

### ISSUE THREAD

**Issue by murithigeo** [opengeospatial/ets-ogcapi-features10#234]
`Part 1: /req/core/fc-numberMatched`
> If a property numberMatched is included in the response, the value SHALL be identical to the number of features in the feature collections that match the selection parameters like bbox, datetime or additional filter parameters.

I'm using sequelize with the method `findAndCountAll` which returns the `count`, which is the number of features that matched the parameters and `rows` which is the features array.
According to the requirement above, then numberMatched would be equal to the `count`. 

`Part 1: /req/core/fc-numberReturned`
> If a property numberReturned is included in the response, the value SHALL be identical to the number of features in the response.

Shouldn't this be the length of the features array?
I had solved this issue in my project but the error has returned and I really didn't understand the solution that @tomkralidis used in #188

**Comment by dstenger** [comment]
Where exactly is the method `findAndCountAll` defined you are describing in your first paragraph? In the test suite there is no such method.

Second paragraph: Can you please document the exact error message of TEAM Engine?

**Comment by murithigeo** [comment]
> Where exactly is the method findAndCountAll defined you are describing in your first paragraph? In the test suite there is no such method.
I'm using sequelize as an ORM to connect to my postgis database, which admittedly make its hard to reproduce the issue. `count` is the number of features matching parameters and `rows` is the features array.

>Second paragraph: Can you please document the exact error message of TEAM Engine?

- Method Name:validateFeaturesResponse_NumberMatched  java.lang.AssertionError: Value of numberReturned (10) does not match the number of features in all responses (410) expected <br>[410] but found <br>[10]
- validateFeaturesWithLimitResponse_NumberMatched  java.lang.AssertionError: Value of numberReturned (52) does not match the number of features in all responses (452) expected <br>[452] but found <br>[52]
- MethodName: validateFeaturesWithLimitResponse_NumberMatched9   java.lang.AssertionError: Value of numberReturned (5) does not match the number of features in all responses (405) expected <br>[405] but found <br>[5]
- Method Name:validateFeaturesWithBoundingBoxResponse_NumberMatched17   java.lang.AssertionError: Value of numberReturned (10) does not match the number of features in all responses (410) expected <br>[410] but found <br>[10]
- Method Name:validateFeaturesWithBoundingBoxResponse_NumberMatched26   java.lang.AssertionError: Value of numberReturned (10) does not match the number of features in all responses (410) expected <br>[410] but found <br>[10]
- Method Name:validateFeaturesWithBoundingBoxResponse_NumberMatched113   java.lang.AssertionError: Value of numberReturned (10) does not match the number of features in all responses (410) expected <br>[410] but found <br>[10]
