### ISSUE TITLE
Wrong result validating LineString crossing dateline-crossing bbox leading to failed test on certified implementation

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-features10#247]
**Describe the bug**
Our previously certified https://maps.gnosis.earth demo implementation is now failing a test caused by wrong LineString / BBOX intersection result.

The failing test is:

Implements A.2.7. Features {root}/collections/{collectionId}/items - BoundingBox, Abstract Test 15: (Requirement /req/core/fc-bbox-response) | [Details ↗](http://opengeospatial.github.io/ets-ogcapi-features-1.0/apidocs/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox#validateFeaturesWithBoundingBoxResponse)

Note that the _Details_ link is broken ( https://opengeospatial.github.io/ets-ogcapi-features-1.0/apidocs/org/opengis/cite/ogcapifeatures10/conformance/core/collections/FeaturesBBox#validateFeaturesWithBoundingBoxResponse ).

I believe the corresponding request is:

https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:physical:ne_10m_land_ocean_seams/items.json?bbox=177.0000000%2C65.0000000%2C-177.0000000%2C70.0000000

The result is [Feature 2](https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:physical:ne_10m_land_ocean_seams/items/2) which is a WGS84 bounding box in the form of a LineString. This LineString **DOES** intersect the request bounding box of (177,65) - (-177,70) which crosses the dateline, which is included (twice, at -180 and +180) in the segments of that LineString feature.

**To Reproduce**
Run the deployed TeamEngine on https://maps.gnosis.earth/ogcapi with the default options

**Expected behavior**
All tests should pass.
The BBOX / LineString test should detect an intersection for this feature 2.

**Screenshots**
![failure](https://github.com/user-attachments/assets/b6d6a919-5d3b-465f-b3d3-d42636437372)

**Additional context**
TEAM Engine would be 100x easier to use if it would include the associated failing request in the test results.

https://cite.opengeospatial.org/teamengine/reports/jerstlouis5/s0001/result/

It also seems that these session results still do not require any kind of authentication.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by dstenger** [comment]
@bpross-52n You could try to set points at 180°/-180° when creating the polygon which is used for the intersection.
This could also mean that the polygon is split into two halves. One is located in the far east and the other one in the far west.
