### ISSUE TITLE
Update implementation to OGC API - Features 1.0 spec

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-ogcapi-features10#45]
OGC API - Features 1.0 Specification: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html

Working Branch:https://github.com/opengeospatial/ets-ogcapi-features10/tree/updateEts-45

**Comment by dstenger** [comment]
Right after TC Meeting in Leuven a new version of ATS will be released including major changes.
Following tasks come up:
* Identify changes in test suite structure and test implementations.
* Update test implementations.
* Update test suite structure (e.g. TestNG configuration, class and method names, description of single tests, and documentation).

**Comment by dstenger** [comment]
ATS in specification was updated: https://github.com/opengeospatial/ogcapi-features/issues/112.
Thus, the test suite must be checked regarding this update.

**Comment by lgoltz** [comment]
## Update

**A.2.1. General Tests** 
* Reference: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_general_tests
* Commit: https://github.com/opengeospatial/ets-ogcapi-features10/commit/fc6d2e9eb0e86a9a9dcfa535c815245a495d518d
* Untested: 
  * A.2.1.1. HTTP Test Method 2
  * A.2.1.2. CRS 84

**Comment by lgoltz** [comment]
## Failures/Typos in Specification
* A.2.1.1. HTTP, Typo: 
  * => approprate
* A.2.3. API Definition Path {root}/api (link)
  * => Duplicate Test Purpose
*  A.2.5. Feature Collections {root}/collections, Abstract Test 10, test Method 1 and 2 
   * => Invalid references

**Comment by lgoltz** [comment]
Data provider was not erroneous  (https://github.com/opengeospatial/ets-ogcapi-features10/commit/706378a27b5f4bd7130fa2e471facb96679c0ddc) but the response could not be identified. Fixed with https://github.com/opengeospatial/ets-ogcapi-features10/commit/61e136e74a9d761735a0f0bfff02d17a0830e22c
