### ISSUE TITLE
Rename parameter 'time' to 'datetime'

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-ogcapi-features10#65]
It looks like the specification was recently updated to rename `time` to `datetime` (requirement 22). When configuring my WFS3 with `datetime` everything seems to work, but configuring with `time` I get a Java exception.

**Comment by lgoltz** [comment]
The ets is outdated. We have to rename `time` to `datetime`.
I assume you get the failure if you are using `datetime`, not `time` as described above?

**Comment by tomkralidis** [comment]
Correct.

**Comment by tomkralidis** [comment]
FYI this issue seems to be present when pulling from Docker via https://github.com/opengeospatial/ets-ogcapi-features10/blob/master/src/site/asciidoc/how-to-run-the-tests.adoc#3-docker
