### ISSUE TITLE
Use this test suite as base for OGC API Common test suite?

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#67]
Is there demand for an OGC API Common test suite?

Current status of OGC API Common specification: https://github.com/opengeospatial/oapi_common

**Comment by dstenger** [comment]
Even if there is no demand for a stand alone test suite, it would be worth developing one:
An OGC API Common test suite could be used as (Java) library or template for other OGC API test suites providing basic tests and functionalities.

**Comment by ghobona** [comment]
Closing this issue because we now use the OGC API - Features test suite as a starting point for developing ETS's of other OGC APIs. We have done so for the Tiles, EDR and Processes APIs.
