### ISSUE TITLE
Change title, short name and description to reflect OGC API - Features

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-features10#73]
The URI (handle) can be kept the same but the title and description should reflect the new name of `OGC API - Features`.

**Comment by dstenger** [comment]
Abbreviation of `OGC API - Features` is discussed in: https://github.com/opengeospatial/oapi_common/issues/35

**Comment by dstenger** [comment]
Working branch: https://github.com/opengeospatial/ets-wfs30/tree/setNameOfTestSuiteToOGCAPIFeatures-73

**Comment by lgoltz** [comment]
Branch: https://github.com/opengeospatial/ets-ogcapi-features-1.0/tree/updateEtsTo-17-069r3-2019-10-07-45

Commit: https://github.com/opengeospatial/ets-ogcapi-features-1.0/commit/91d293f1fb0479ba42d96624cb0bcc0cc6f8dc01
