### ISSUE TITLE
Review and test update to OGC API - Features spec

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-features10#80]
Current status:
* Latest release is installed on Beta environment: http://cite.opengeospatial.org/te2/

Tasks:
* Collecting feedback of other users testing their own implementations.
* Review of https://github.com/opengeospatial/ets-ogcapi-features10/issues/45.

**Comment by cportele** [comment]
@dstenger 

I did a test with the following API: https://services.interactive-instruments.de/t15/daraa/

I get several errors that I do not understand.

One error is `timeStamp in response must be after the request was send (2019-12-09T12:11:17.553Z) but was '2019-12-09T12:11:17Z'` which does not seem justified as milliseconds are optional.

One option could be to change FeaturesAssertions from

````java
        assertTrue( date.isAfter( timeStampBeforeResponse ),
                    "timeStamp in response must be after the request was send (" + formatDate( timeStampBeforeResponse )
````

to

````java
        assertTrue( !date.isBefore( timeStampBeforeResponse.truncatedTo(ChronoUnit.SECONDS) ),
                    "timeStamp in response must not be before the request was send (" + formatDate( timeStampBeforeResponse.truncatedTo(ChronoUnit.SECONDS) )
````

There are also other errors where a `limit` is used that is larger than the maximum limit, but the assertion expects a 200 response?

**Comment by dstenger** [comment]
@cportele 

Thank you for the feedback.

Regarding timeStamp: Yes, we agree that your proposed implementation is more generic. We will adjust the implementation.

Regarding limit: The test targets `Requirement 21 - /req/core/fc-limit-response - A`. From our understanding the spec states that the maximum number of features is returned when limit exceeds maximum. Otherwise, shouldn't the spec demand an exception explicitly? Also, `Permission 6 - /per/core/fc-limit-response-2` backs up our understanding.
However, we agree that the test verifies a special case. We will also add a more common use case (abstract test is not very detailed here).

**Comment by cportele** [comment]
> Regarding limit: The test targets Requirement 21 - /req/core/fc-limit-response-1 - A. From our understanding the spec states that the maximum number of features is returned when limit exceeds maximum. Otherwise, shouldn't the spec demand an exception explicitly? Also, Permission 6 - /per/core/fc-limit-response-2 backs up our understanding.

The requirement /req/core/fc-limit-response-1 requires that the response never contains more features than the value of `limit` in the request or than the `maximum` of the limit parameter in the API definition.

If the value of `limit` is higher than the `maximum` this is an error as it does not fit the API definition and the API must return a 400 response. See also http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_error_situations_6:

> A 400 will be returned in the following situations:
> * If query parameter limit is not an integer or not between minimum and maximum;
> * ...

**Comment by lgoltz** [comment]
Removed test with limit > maximum: https://github.com/opengeospatial/ets-ogcapi-features10/commit/61e136e74a9d761735a0f0bfff02d17a0830e22c

**Comment by dstenger** [comment]
Thank you for the hint. We fixed the limit test.

Also, the timeStamp test was improved.

**Comment by cportele** [comment]
Thank you, looks good now:

`<testng-results skipped="0" failed="0" total="107" passed="107">`

**Comment by cportele** [comment]
I have made some additional tests and created #82 as a result.
