### ISSUE TITLE
Docker image for the last 0.5 tag

### ISSUE THREAD

**Issue by pblottiere** [opengeospatial/ets-ogcapi-features10#83]
Hello everyone,

I noticed that the testsuite has been updated for the final specification of the API. Do you plan to release a new Docker image for the last 0.5 tag?

Thanks a lot for your work!

**Comment by dstenger** [comment]
Hi,
We already created a tagged Docker Image but the repository name changed: https://hub.docker.com/r/ogccite/ets-ogcapi-features10
Regards,
Dirk

**Comment by pblottiere** [comment]
Hi Dirk,

> We already created a tagged Docker Image but the repository name changed: https://hub.docker.com/r/ogccite/ets-ogcapi-features10

Nice, thanks:+1:! I'm going to test it asap on QGIS Server :).

Have a good day.
