### ISSUE TITLE
pygeoapi beta testing

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-ogcapi-features10#85]
Testing http://cite.opengeospatial.org/te2 against http://147.102.109.27:5001 yields no failures but numerous skipped tests.

Skipped test root causes:

- `org.testng.SkipException: Could not find a response for collection with id canada-hydat-daily-mean-02hc003`
- `org.testng.SkipException: Could not find url for collection with id canada-hydat-daily-mean-02hc003 supporting GeoJson (type application/geo+json)`

Any idea how to address these ?

**Comment by tomkralidis** [comment]
CITE beta details:
- username: tomkralidis
- session: s0078

**Comment by dstenger** [comment]
Can you please check if the feature collection in JSON format contains the correct link to the features?
Following information is important (rel and type must be set correctly):
```
...
  "links": [
    {
      "href": "http://test-service.de/collections/collection/items",
      "rel": "items",
      "type": "application/geo+json",
...
```

**Comment by tomkralidis** [comment]
Thanks @dstenger .  I deleted/created another test session (s0078) and these issues were resolved.  At this point, I am getting 3 failures of type:

- `java.lang.AssertionError: timeStamp in response must not be after the request was send (2020-01-02T16:11:52Z) but was '2020-01-02T16:11:52.430407Z'`

Any idea on how to fix?

**Comment by dstenger** [comment]
This seems to be a bug in the test suite. Can you please create a new issue for that?

**Comment by tomkralidis** [comment]
Thanks for the valuable feedback @dstenger.  Closing this issue in lieu of #86
