### ISSUE TITLE
How to spot the root cause among several skipped tests?

### ISSUE THREAD

**Issue by pblottiere** [opengeospatial/ets-ogcapi-features10#87]
Hello everyone,

I'm currently trying to run ets-ogcapi-features10 on QGIS Server thanks to the corresponding [docker image](https://hub.docker.com/r/ogccite/ets-ogcapi-features10).

Below a screenshot of the TeamEngine report:

![cite](https://user-images.githubusercontent.com/9266424/72170186-b8829080-33d0-11ea-8aba-cae8e2c21923.png)

From what I understand, a lot of tests are `Skipped` because there're some errors in other tests. For example: `SkipException: ApiModel is not available` or `depends on not successfully finished methods`.

However, I've some difficulties to spot the root cause of the problem. I think it's the `openapi Document Retrieval` test because the corresponding message is a bit different: `SkipException: Path to the API Definition could not be constructed from the landing page`. Am I right?

BTW, do you think it could be possible to have the root cause of the problem clearly mentioned as a failing test?

Thanks and have a great day/night!

**Comment by dstenger** [comment]
Hi,

Yes, I also assume that the `openapi Document Retrieval` is the root cause of your problem.

Also, I agree that this test should fail instead of being skipped. Otherwise, this would be a valid test result.

Is this service publicly available so that we can use it for testing?

**Comment by pblottiere** [comment]
Hi @dstenger,

> Is this service publicly available so that we can use it for testing?

Yes it is: http://138.201.120.72:8084/qgisserver_demo_wfs3/wfs3/

Thanks for your quick response :+1:

**Comment by keshav-nangare** [comment]
@dstenger 

Updated the test `openapiDocumentRetrieval` which will fail if apiUrl is null.

Following is the new result:
![image](https://user-images.githubusercontent.com/14732650/74674598-c26d8f80-51d7-11ea-8593-c0d2762c301c.png)

**Comment by pblottiere** [comment]
> Updated the test openapiDocumentRetrieval which will fail if apiUrl is null.
> Following is the new result:

Awesome :).

And just out of curiosity, when do you plan to have a new release/Docker image with these modifications?

Thanks again for your work :+1:!

**Comment by dstenger** [comment]
In your service the wrong `type` is set.
```
href: "http://138.201.120.72:8084/qgisserver_demo_wfs3/wfs3/api?"
rel: "service-desc"
title: "API description"
type: "application/openapi+json;version=3.0"
```
It should be `application/vnd.oai.openapi+json;version=3.0` instead.

**Comment by dstenger** [comment]
We will release this test suites in the next weeks again.

**Comment by pblottiere** [comment]
> It should be application/vnd.oai.openapi+json;version=3.0 instead.

Oh, thanks for the tip!

> We will release this test suites in the next weeks again.

Great :+1:
