### ISSUE TITLE
Tests fail if 'unknownQueryParameter' is declared in the API, or if the API allows for any extra parameter

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-ogcapi-features10#89]
Tests like https://github.com/opengeospatial/ets-ogcapi-features10/blob/a7eb2a19fb47fc6523c82a283f18794a2f6390a7/src/main/java/org/opengis/cite/ogcapifeatures10/collections/FeaturesErrorConditions.java#L113
should be check:

- If ``unknownQueryParameter`` is declared in the API (and not run, or use some other name)
- If the API is designed to allow additional freeform parameters (and not run this test)

See also discussion at https://github.com/opengeospatial/ogcapi-features/issues/128

**Comment by dstenger** [comment]
Thanks for reporting. We will improve/fix the implementation.
